pipeline {
  agent any
    
  tools {nodejs "NodeJS"}
    
  stages {
        
    stage('Git') {
      steps {
        git 'https://github.com/darwinmc/simple-node-js-react-npm-app'
      }
    }
     
    stage('Build') {
      steps {
        sh 'npm install'
    
      }
    }  
    
            
    stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
  }
}
